services:
  rate-limiter-memory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=memory
      - JAVA_OPTS=-Xmx1g -Xms512m -XX:+UseG1GC -XX:+UseContainerSupport
      - SERVER_PORT=8080
    restart: unless-stopped
    container_name: rate-limiter-memory
    networks:
      - memory-network

networks:
  memory-network:
    name: rate-limiter-memory-network
    driver: bridge