server:
  port: 8080
spring:
  profiles:
    active: memory

rate-limit:
  clients:
    client-1:
      requests-per-minute: 5
      burst-capacity: 3
    client-2:
      requests-per-minute: 15
      burst-capacity: 8
  storage:
    type: memory

---
spring:
  config:
    activate:
      on-profile: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

rate-limit:
  storage:
    type: redis