server:
  port: 8080
spring:
  profiles:
    active: memory

rate-limit:
  clients:
    client-1:
      requests-per-minute: 5
      burst-capacity: 3
    client-2:
      requests-per-minute: 15
      burst-capacity: 8
  storage:
    type: memory

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: Rate Limiting API
    description: API demonstrating rate limiting with different algorithms
    version: 1.0.0

---
spring:
  config:
    activate:
      on-profile: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

rate-limit:
  storage:
    type: redis